version: '3'

services:
  java-app:
    image: java-app:1.6
    container_name: java-app
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PWD: "${DB_PWD}"
      DB_SERVER: "${DB_SERVER}"
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PWD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8083:80"
    networks:
      - mynetwork

volumes:
  mysql-data:
    driver: local

networks:
  mynetwork:
    driver: bridge